sudo: required
language: node_js
node_js:
  - '6'
branches:
  only:
  - master
  - develop
services:
  - mongodb
  - docker
cache:
  directories:
  - $HOME/.yarn-cache
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - cd src
  - yarn --pure-lockfile
before_script:
  - sleep 15
script:
  - npm run test-cov-lcov
after_success:
  - cat ./lcov.info | ./node_modules/.bin/coveralls
notifications:
  slack:
    secure: J/lOLe9y6fUPSb83GB2ipFCsJXlBfrEaS8glqpTxQImcAV49Dzi/sgw4bVE7AP7yPNlJCdVGW2/jgesR3Gz9XOJW6aTziqyO171EyRoNmecgzI9rXgLRQtpf0q0R92PXb84ZAnSdZlrq5qmHtV477UWTpTn9Csogk9SVbVZityBcJTtY1fKPh3P9is0uWOMY4uJ8kW6AoibRCsmOBEpVMAqR+2m8EUxACj2ZZcAEIX8Ou9bf/a3pzFd+p4aor3c/uIz1lV8yEBPDmu34OxW6YYYF4jb6M2cL/2uYin6ne5Dbk0owllgAAOPQARVNOG8bPSrUI4ipOwF/d+vs6gSyeAhOKbqTcITXYpJEP9biGP6mjl1xhogh9YVzIW07ecgp0bO0tAXKbrfuKV5ViCXKwazLCI/Nz3y1rIKO7GMigsC41cwomOewVJmNRtHXJyyyCOQfrlsB/OYd6ri/8lHUi5r+xsbqjarN8Nkqfg851ih5ldDLW3GzovV1kaVKxL/TuRZU3mRZhlCzxJBNl5gfJWNmNGaAQDoN/+fIfOWFID3v43vQaDWbcxAqQe2wTStCJFMzOk8aeBLdJhrCvPKh8FErDLGqjQ8DsfnbFA3eZztjXJZJ/iX6mu24U9fcA27Z01mfZLc+ogRpvnz7MBZkttDJ0Lgc9axPzHgdGzMVGiY=
