gateway:
  image: ncornag/micro-docker-nginx
  ports:
    - 80:80
  links:
    - consul:consul
  restart: always

consul:
  image: consul:latest
  ports:
    - 8501:8500
  restart: always
  command: agent -log-level info -dev -client 0.0.0.0 -bind 0.0.0.0

mongo:
  image: mongo:3
  ports:
    - 27018:27017

bus:
  image: rabbitmq:3-management
  ports:
    - 15673:15672
    - 5673:5672

elasticsearch:
  image: elasticsearch:2
  ports:
  - 9201:9200
  - 9301:9300

redis:
  image: redis:3
  ports:
  - 6380:6379

logstash:
  image: logstash:2
  expose:
  ports:
  - 28778:28777
  volumes:
  - ./dockerConf/logstash:/config-dir
  links:
  - elasticsearch:elasticsearch
  command: logstash -f /config-dir/elastic.conf

kibana:
  image: kibana:4
  ports:
  - 5601:5601
  links:
  - elasticsearch:elasticsearch

stock-service:
  build: ./micro-stock-service
  links:
  - gateway:gateway
  - consul:consul
  - mongo:mongo
  - bus:bus

catalog-service:
  build: ./micro-catalog-service
  links:
  - gateway:gateway
  - consul:consul
  - mongo:mongo
  - bus:bus
  - elasticsearch:elasticsearch

cart-service:
  build: ./micro-cart-service
  links:
  - gateway:gateway
  - consul:consul
  - bus:bus
  - mongo:mongo

tax-service:
  build: ./micro-tax-service
  links:
  - gateway:gateway
  - consul:consul
  - bus:bus
  - mongo:mongo
  - logstash:logstash

promotion-service:
  build: ./micro-promotion-service
  links:
  - gateway:gateway
  - consul:consul
  - bus:bus
  - mongo:mongo
