version: '2'

services:

  consul:
    image: consul:latest
    ports:
      - 8501:8500
    environment:
      - LOGSPOUT=ignore
    restart: always
    command: agent -log-level info -dev -client 0.0.0.0 -bind 0.0.0.0

  gateway:
    image: ncornag/micro-docker-nginx
    ports:
      - 80:80
    environment:
      - LOGSPOUT=ignore
    links:
      - consul
    restart: always
    depends_on:
      - consul

  mongo:
    image: mongo:3
    ports:
      - 27018:27017
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - consul

  bus:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - consul

  elasticsearch:
    image: elasticsearch:2
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - consul

  redis:
    image: redis:3
    ports:
      - 6380:6379
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - consul

  logstash:
    image: logstash:2
    ports:
      - 5000:5000
      - 5000:5000/udp
    environment:
      - LOGSPOUT=ignore
    volumes:
      - ./dockerConf/logstash:/config-dir
    links:
      - elasticsearch
    command: logstash -f /config-dir/elastic.conf

  logspout:
    image: gliderlabs/logspout
    environment:
      - ROUTE_URIS=syslog://logstash:5000
      - LOGSPOUT=ignore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - logstash
    depends_on:
      - logstash

  kibana:
    image: kibana:4
    ports:
      - 5602:5601
    environment:
      - LOGSPOUT=ignore
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  stock-service:
    build: ./micro-stock-service
    links:
      - gateway
      - consul
      - mongo
      - bus
    depends_on:
      - consul
      - mongo
      - bus
      - logspout

  catalog-service:
    build: ./micro-catalog-service
    links:
      - gateway
      - consul
      - mongo
      - bus
      - elasticsearch
    depends_on:
      - consul
      - mongo
      - bus
      - logspout

  cart-service:
    build: ./micro-cart-service
    links:
      - gateway
      - consul
      - bus
      - mongo
    depends_on:
      - consul
      - mongo
      - bus
      - logspout

  tax-service:
    build: ./micro-tax-service
    links:
      - gateway
      - consul
      - bus
      - mongo
    depends_on:
      - consul
      - mongo
      - bus
      - logspout

  promotion-service:
    build: ./micro-promotion-service
    links:
      - gateway
      - consul
      - bus
      - mongo
    depends_on:
      - consul
      - mongo
      - bus
      - logspout
