version: '2'

services:

  service:
    environment:
      - CONSUL=consul
    mem_limit: 128m
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
