version: '2'

services:

  consul:
      image: consul:v0.7.0
      restart: always
      mem_limit: 128m
      ports:
        - 8501:8500
      command: agent -log-level info -server -client=0.0.0.0 -bind 0.0.0.0 -bootstrap -ui

  gateway:
      image: ncornag/micro-docker-nginx
      restart: always
      mem_limit: 128m
      environment:
        - CONSUL=consul
        - CONSUL_AGENT=1
#        - CONSUL_SERVER=1
      ports:
#        - 8501:8500
        - 80:80
        - 443
        - 9090 # containerpilot telemetry

  mongo:
    image: mongo:3
    ports:
      - 27018:27017
    volumes:
      - ./dockerConf/mongo/data:/data/db

  bus:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672

  elasticsearch:
    image: elasticsearch:2
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - ./dockerConf/elasticsearch/data:/usr/share/elasticsearch/data

  redis:
    image: redis:3
    ports:
      - 6380:6379

  logstash:
    image: logstash:2
    ports:
      - 12201:12201
      - 12201:12201/udp
    expose:
      - 5000
      - 12201
    volumes:
      - ./dockerConf/logstash:/config
    links:
      - elasticsearch
    command: logstash -f /config/logstash.conf

  kibana:
    image: kibana:4
    ports:
      - 5602:5601
    environment:
      - LOGSPOUT=ignore
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  stock-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-stock-service
    links:
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  catalog-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-catalog-service
    links:
      - gateway
      - mongo
      - bus
      - elasticsearch
    depends_on:
      - mongo
      - bus

  cart-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-cart-service
    links:
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  tax-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-tax-service
    links:
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  promotion-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-promotion-service
    links:
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus
